source 'https://github.com/CocoaPods/Specs.git' 
use_frameworks!

target 'CloudConvertExample' do
	pod 'CloudConvert', :path => '..'
end

#pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'xcode-6.3'